In [6]:
#Array Value from user in python
from array import *

arr = array('i', [])

Length = int(input("Enter the lenght: "))

for i in range(Length):
    x = int(input("Enter the value: "))
    arr.append(x)
print(arr)

val = int(input("Enter the searching element: "))
k = 0
for j in (arr):
    if j == val:
        print(k)
        break
    k += 1


ValueError: invalid literal for int() with base 10: ''

In [7]:
#numpy for multidimentional Array
from numpy import *
arr = array([1,2,3,4,5,6,7])
arr1 = array([1,2,3,4,5,6,7.5])
print(arr.dtype)
print(arr1.dtype)

int64
float64


In [ ]:
ar = linspace(0,15,16)
print(ar)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [ ]:
ar = linspace(5,16,20)
print(ar)

[ 5.          5.57894737  6.15789474  6.73684211  7.31578947  7.89473684
  8.47368421  9.05263158  9.63157895 10.21052632 10.78947368 11.36842105
 11.94736842 12.52631579 13.10526316 13.68421053 14.26315789 14.84210526
 15.42105263 16.        ]


In [ ]:
arr = arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
arr = logspace(1,40,5)
print('%.2f' %arr[1])

56234132519.03


In [4]:
from numpy import *
arr1 = array([
                [1,2,3,4],
                [5,6,7,7]


             ])
print(arr1)

[[1 2 3 4]
 [5 6 7 7]]


In [8]:
from numpy import *
arr1 = array([
                [1,2,3,4],
                [5,6,7,7]



             ])
arr2 = arr1.flatten()
            
print(arr2.dtype)
print(arr2.shape)
print(arr2.ndim)
print(arr2)

int64
(8,)
1
[1 2 3 4 5 6 7 7]


In [14]:
from numpy import *
arr1 = array([
                [1,2,3,4,5,9],
                [5,6,7,7,8,0]
             
             
             ])
arr2 = arr1.flatten()
arr3 = arr2.reshape(3,4)
print(arr3)

arr4 = arr2.reshape(2,2,3)
print(arr4)


[[1 2 3 4]
 [5 9 5 6]
 [7 7 8 0]]
[[[1 2 3]
  [4 5 9]]

 [[5 6 7]
  [7 8 0]]]


In [1]:
from numpy import *
m = matrix('1,2 ; 3,4 ; 5,6')
print((m))

[[1 2]
 [3 4]
 [5 6]]


Functions in python

In [2]:
def update(lst):
    print(id(lst))

    lst[1] = 25
    print(id(lst))
    print("x ", lst)
    pass

lst = [10,20,30]
print(id(lst))
update(lst)
print("lst ", lst)

140152209313344
140152209313344
140152209313344
x  [10, 25, 30]
lst  [10, 25, 30]


In [12]:
#different types of arguments in python
#multiple arguments from the user
def person(name, **data):
    print(name)
    print(data)
    for i,j in data.items():
        print(i,j)
person('Aniket',age=21, city='Muzaffarnagar',mob=8491062)

Aniket
{'age': 21, 'city': 'Muzaffarnagar', 'mob': 8491062}
age 21
city Muzaffarnagar
mob 8491062


In [14]:
a=9
print(id(a))

def something():
    a=10

    x = globals()['a']
    print(id(x))
    print("in", a)

    globals()['a'] = 15

something()
print("out", a)

9788864
9788864
in 10
out 15


In [15]:
#pass list to a function
def count(int):
    even = 0
    odd = 0
    for i in lst:
        if i%2==0:
            even +=1
        else:
            odd += 1
    return even, odd

 
lst = [20,25,30,35,40,45,50,55]
even, odd = count(lst)
print(even, odd)

4 4


In [29]:

def count(str):
    string = []
    for i in lst:
        if len(i) == k:
            string.append(i)

    
    return string
        
k = 5
lst = ["Aniket", "Verma", "Banana", "Mango"]
name = count(lst)
print(name)

['Verma', 'Mango']


In [1]:
#fibonacci series

def fib(n):
    a = 0
    b = 1
    for i in range(2,n):
        c = a+b
        a,b = b,c
        if c <= 100:
            print(c)
            


fib(100)

1
2
3
5
8
13
21
34
55
89


In [25]:
#factorial number via recurssion
def fact(n):
    if n ==1:
        return 1
    else:
        return n * fact(n-1)#function call itself

pn = fact(5)
print(pn)

120


In [5]:
import sys
sys.setrecursionlimit(2000)
print(sys.getrecursionlimit())
i = 0
def greet():
    global i
    print('Hello!', i)
    i+=1
    
greet()



2000
Hello! 0


In [32]:
import sys
sys.stdout.write("Hello, World!")

Hello, World!

In [34]:
#lamda function
f = lambda a,b : a+b #a,b are the argumentss which is passes by the user and this function can take merely one operation at particuler time
print(f(5,6))

11


In [39]:
a = (1,2,3,5,4)
b = (2,5,6,8,9)
c = dict(zip(a,b))
print(c)

{1: 2, 2: 5, 3: 6, 5: 8, 4: 9}


In [54]:
#rivision
def palindrom(n):
    rev = 0
    a = n
    while n > 0:
        m = n % 10
        rev = rev*10+m
        n//=10
    
    print(rev)

palindrom(965)

569


In [48]:
def Armstrong(n):
    sum = 0
    x = n
    while n>0: 
        a = n%10
        sum = sum  + a**3
        n//=10
    if sum==x:
        print ("Number is Armstrong")
        return sum
    else:
        print("number is not Armstrong")
n = 5668
result = Armstrong(n)
print("Armstrong number is: ", Armstrong(n))

number is not Armstrong
number is not Armstrong
Armstrong number is:  None


In [1]:
#lambda function
nums = [1,2,3,4,5,6,7,8,9]
evens = list(filter(lambda n : n%2 == 0, nums))#we use filter
print(evens)
odds = list(filter(lambda n : n%2!=0, nums))
print(odds)
double = list(map(lambda n : n*2, evens))
print(double)
from functools import reduce
sum = reduce(lambda a,b : a+b, double)
print(sum)

[2, 4, 6, 8]
[1, 3, 5, 7, 9]
[4, 8, 12, 16]
40


In [2]:
#decorators
def div(a,b):
    print(a/b)

def smart_div(func):
    def inner(a,b):
        if a<b:
            a,b = b,a
        return func(a,b)
    return inner

div = smart_div(div)
div(2,4)


2.0
